name: OpenShift Image Upgrade

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Image Tag"
        required: true
        default: "1.27.2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/
          oc version --client

      - name: Login
        run: |
          oc login \
            --token="$OPENSHIFT_TOKEN" \
            --server="$OPENSHIFT_SERVER"

      - name: Verify
        run: |
          oc whoami
          oc project "$OPENSHIFT_NAMESPACE"
          oc get deployment