name: OpenShift Image Upgrade

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        run: |
          echo "OpenShift workflow started"