name: OpenShift Image Upgrade

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Image Tag"
        required: true
        default: "1.27.2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/
          oc version --client

      - name: Login to OpenShift
        run: |
          oc login \
            --token="$OPENSHIFT_TOKEN" \
            --server="$OPENSHIFT_SERVER"

      - name: Select Project
        run: |
          oc project "$OPENSHIFT_NAMESPACE"

      - name: Current Image
        run: |
          echo "Current Image:"
          oc get deployment nginx-app \
          -o jsonpath='{.spec.template.spec.containers[0].image}'
          echo ""

      - name: Update Image
        run: |
          oc set image deployment/nginx-app \
          nginx=nginxinc/nginx-unprivileged:${{ github.event.inputs.imageTag }}

      - name: Verify Rollout
        run: |
          oc rollout status deployment/nginx-app --timeout=120s

      - name: Show Updated Image
        run: |
          echo "Updated Image:"
          oc get deployment nginx-app \
          -o jsonpath='{.spec.template.spec.containers[0].image}'
          echo ""

      - name: Email Success
        if: success()
        run: |
          echo "Deployment upgraded successfully to version ${{ github.event.inputs.imageTag }}"

      - name: Rollback
        if: failure()
        run: |
          oc rollout undo deployment/nginx-app

      - name: Verify Rollback
        if: failure()
        run: |
          oc rollout status deployment/nginx-app

      - name: Email Failure
        if: failure()
        run: |
          echo "Deployment failed. Rollback completed."